COPY ~KhaeNPC/items/K3WEDR.itm~ ~override~
SAY NAME1 @0
SAY NAME2 @0
SAY DESC ~This is a silver ring with a pearl with powerful protective magic..

STATISTICS:

Equipped Abilities
- Saving Throws: +2
- Magic Resistance: +15%

Weight: 1~

COPY ~KhaeNPC/items/K3STDI.itm~ ~override~
SAY NAME1 @2
SAY NAME1 @2
SAY DESC ~Used by most Shadow Thieves. This leather armor makes it easier to hide in the darkness, and many slots for throwing knives.

STATISTICS:

Weight: 25~ 