IF
    Global("K3DEBT","GLOBAL",1)
THEN
	RESPONSE #100
		CutSceneId(Player1)	
        FadeFromColor([30.0],0)
        Wait(2)
        ActionOverride("K3DEB1",Enemy())
        Wait(1)
        ActionOverride("K3DEB2",Enemy())
        Wait(1)
        ActionOverride("K3DEB3",Enemy())
        Wait(2)
        EndCutSceneMode()
        SetGlobal("K3DEBT","GLOBAL",2)
        ActionOverride("K3KHAE",StartDialogueNoSet(Player1)) // This work
END